### ISSUE TITLE
Problem while reading aedb file with Edb:  Could not load file or assembly 'Ansys.Ansoft.Edb'

### ISSUE THREAD

**Issue by zolabar** [ansys/pyedb#622]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I want to assign s-parameters to capacitor components in an hfss 3d layout aedt file, via pyedb in order be able to automize this workflow step, see 

https://github.com/ansys/pyaedt/discussions/4818

But I get error messages aleady when reading the file in...

DotNet Core correctly loaded.
PyEDB INFO: StdOut is enabled
PyEDB INFO: Logger is initialized in EDB.
PyEDB INFO: legacy v0.17.0
PyEDB INFO: Python version 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]
Traceback (most recent call last):
  File "/PyAnsys/capacitor_s.py", line 7, in <module>
    edb = Edb(path, edbversion="2024.1")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/generic/design_types.py", line 110, in Edb
    return app(
           ^^^^
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/dotnet/edb.py", line 209, in __init__
    Database.__init__(self, edbversion=edbversion, student_version=student_version)
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/dotnet/edb_core/dotnet/database.py", line 829, in __init__
    EdbDotNet.__init__(self, edbversion=edbversion, student_version=student_version)
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/dotnet/edb_core/dotnet/database.py", line 759, in __init__
    _clr.AddReference("Ansys.Ansoft.Edb")
System.IO.FileNotFoundException: Could not load file or assembly 'Ansys.Ansoft.Edb, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Ansys.Ansoft.Edb, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Python.Runtime.AssemblyManager.LoadAssembly(AssemblyName name) in /tmp/build-via-sdist-s1jxy7eq/ansys-pythonnet-3.1.0rc3/src/runtime/AssemblyManager.cs:line 227
   at Python.Runtime.CLRModule.AddReference(String name) in /tmp/build-via-sdist-s1jxy7eq/ansys-pythonnet-3.1.0rc3/src/runtime/Types/ClrModule.cs:line 107

### Steps To Reproduce

A hfss 3D layout aedt aedb project called package.aedb, there I ran a python (python 3.11.3) script with the code

``` python

from pyedb import Edb
import os

path = os.path.join(os.getcwd(), "package.aedb")

edb = Edb(path, edbversion="2024.1")

edb.close_edb()

```

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.10

### Installed packages

annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.15.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
clr-loader==0.2.6
comm==0.2.2
debugpy==1.8.2
decorator==5.1.1
defusedxml==0.7.1
distro==1.9.0
dotnetcore2==3.1.23
executing==2.0.1
fastjsonschema==2.20.0
fqdn==1.5.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
ipykernel==6.29.4
ipython==8.25.0
ipywidgets==8.1.3
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterlab==4.2.3
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
notebook==7.2.1
notebook_shim==0.2.4
numpy==1.26.4
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
platformdirs==4.2.2
prometheus_client==0.20.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
pyedb==0.17.0
Pygments==2.18.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.0.3
qtconsole==5.5.2
QtPy==2.4.1
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.18.1
Rtree==1.2.0
scipy==1.14.0
Send2Trash==1.8.3
six==1.16.0
sniffio==1.3.1
soupsieve==2.5
stack-data==0.6.3
terminado==0.18.1
tinycss2==1.3.0
toml==0.10.2
tornado==6.4.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
tzdata==2024.1
uri-template==1.3.0
urllib3==2.2.2
wcwidth==0.2.13
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.11

**Comment by ring630** [comment]
@zolabar the error msg indicates pyedb cannot find AEDT installation. It is related to your system environment. Please let me know if you can run below example on your local machine successfully.

https://edb.docs.pyansys.com/version/stable/examples/legacy_standalone/01_edb_example.html#sphx-glr-examples-legacy-standalone-01-edb-example-py

**Comment by zolabar** [comment]
> @zolabar the error msg indicates pyedb cannot find AEDT installation. It is related to your system environment. Please let me know if you can run below example on your local machine successfully.
> 
> https://edb.docs.pyansys.com/version/stable/examples/legacy_standalone/01_edb_example.html#sphx-glr-examples-legacy-standalone-01-edb-example-py

@ring630 thank you for the feedback.

Probably that is the reason, I can't run those examples, I get errors like

Traceback (most recent call last):
  File "/PyAnsys/assign.py", line 11, in <module>
    targetfile = download_file(path, destination=temp_folder)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/misc/downloads.py", line 332, in download_file
    _download_file(directory, filename, destination, local_paths)
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/misc/downloads.py", line 152, in _download_file
    _retrieve_folder(EXAMPLE_REPO, directory, destination, local_paths)
  File "/PyAnsys/.venv/lib/python3.11/site-packages/pyedb/misc/downloads.py", line 124, in _retrieve_folder
    with urllib.request.urlopen(_get_dir) as response:  # nosec
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/miniconda/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by zolabar** [comment]
Probably I need to check how to assign correctly the environment variables:

export ANSYSEM_ROOT222=/path/to/AedtRoot/AnsysEM/v222/Linux64
export LD_LIBRARY_PATH=$ANSYSEM_ROOT222/common/mono/Linux64/lib64:$ANSYSEM_ROOT222/Delcross:$LD_LIBRARY_PATH

**Comment by zolabar** [comment]
I corrected the variable ANSYSEM_ROOT222, that should be enough, right? But I get the same errors...

**Comment by zolabar** [comment]
@ring630 , it works in Windows. Maybe most of users use pyedb on Windows?

**Comment by ring630** [comment]
@zolabar there are also large number of pyedb users on Linux. By a  second look at the error msg "urllib.error.HTTPError: HTTP Error404: Not Found", I suspect your firewall blocked the downloading.

**Comment by jdzhu19** [comment]
The same problem here, could you please tell me how you solved it in the end? @zolabar
