### ISSUE TITLE
GDS control file example fails

### ISSUE THREAD

**Issue by Devin-Crawford** [ansys/pyedb#708]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The [example](https://edb.docs.pyansys.com/version/stable/examples/legacy_standalone/10_GDS_workflow.html) fails in cell 8.

### Steps To Reproduce

See the example web page.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

The failure is on the runner.

**Comment by ring630** [comment]
@SMoraisAnsys @svandenb-dev all pyedb examples have the same problem in documentation. I cannot reproduce it on my local machine, so I suspect it is related to CICD.

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\actions-runner\_work\_tool\Python\3.10.11\x64\lib\logging\handlers.py", line 74, in emit
    self.doRollover()
  File "C:\actions-runner\_work\_tool\Python\3.10.11\x64\lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\actions-runner\_work\_tool\Python\3.10.11\x64\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ansys\\AppData\\Local\\Temp\\pyedb_ansys.log' -> 'C:\\Users\\ansys\\AppData\\Local\\Temp\\pyedb_ansys.log.1'
```

**Comment by gkorompi** [comment]
fixed in https://github.com/ansys/pyaedt-examples/pull/375
