### ISSUE TITLE
(AO) The new Cpython vertual environment could not support edb.configuration.run(fix_padstack_def=True)

### ISSUE THREAD

**Issue by aohta2021** [ansys/pyedb#951]
After extracting To_Be_1216.zip in a new Cpython environment
Unzip To_Be_1216.zip

 Run_EDB.bat.

 It makes bellow errors.
 
Traceback (most recent call last):
  File "C:\Users\aohta\OneDrive - ANSYS, Inc\Documents\2024_BMT\DENSO\To_Be_1216\pyedb_setup.py", line 57, in <module>
    [To_Be_1216.zip](https://github.com/user-attachments/files/18162769/To_Be_1216.zip)

  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\configuration.py", line 124, in run
    self.cfg_data.components.apply()
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\cfg_components.py", line 254, in apply
    comp.set_parameters_to_edb()
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\cfg_components.py", line 214, in set_parameters_to_edb
    self._pyedb_obj.enabled = self.enabled
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\dotnet\edb_core\cell\hierarchy\component.py", line 210, in enabled
    cmp_prop.SetEnabled(value)
AttributeError: 'IOComponentProperty' object has no attribute 'SetEnabled'
Can you please find out what the problem is?
Newly created Cpython virtual environment:venv310_NG.zip
https://ansys-my.sharepoint.com/:u:/p/akira_ohta/EbriGxMM3eVNoItQ3Xc3PZsBHOkYo0hwcmCi_Ct54eRkCw?e=l7LIKF

This script runs without problems in environments that have been updated to the latest version using
pip install -U pyaedt[all] from the previous environment.

Lib Environment updated to the latest version from the previous environment:venv310_OK.zip
https://ansys-my.sharepoint.com/:u:/p/akira_ohta/EWDlo-EPGEFFjTo3_oljVpABsuXpvzYfe6mswh9sDb4Ryg?e=UQFA0z

**Comment by hui-zhou-a** [comment]
This is not related to env. Only RLC can be enabled or disabled. You can remove "enabled" key from cfg file.

`AttributeError: 'IOComponentProperty' object has no attribute 'SetEnabled'`

**Comment by aohta2021** [comment]
@hui-zhou-a 
Hui-san
Thank you for response.
Please let me know correct cfg format of  edb_configuration.json.
It is in To_Be_1216.zip

I could not run correctly after remove "enabled" key from cfg file.
[edb_configuration.json](https://github.com/user-attachments/files/18173672/edb_configuration.json)

(I found PyEDB could not control model activate/deactivate now.
So I think it is need to control by cfg file.)
But error is occurred as bellow.
PyAEDT INFO: EDB initialized.
Traceback (most recent call last):
  File "C:\Users\aohta\OneDrive - ANSYS, Inc\Documents\2024_BMT\DENSO\To_Be_1216\pyedb_setup.py", line 56, in <module>
    edb.configuration.load(config_file=file_json)
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\configuration.py", line 92, in load
    self.cfg_data = CfgData(self._pedb, **self.data)
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\cfg_data.py", line 60, in __init__
    self.ports = CfgPorts(self._pedb, ports_data=kwargs.get("ports", []))
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\cfg_ports_sources.py", line 123, in __init__
    if p["type"] == "wave_port":
KeyError: 'type'


I  could not run correctly after remove all component assign setting.
[no_cmp_edb_configuration.json](https://github.com/user-attachments/files/18173196/no_cmp_edb_configuration.json)


The error has been occurred on New env.
Error Message
  File "C:\Users\aohta\venv310\lib\site-packages\pyedb\configuration\configuration.py", line 140, in run
    temp[name] = pdef.get_properties()
AttributeError: 'EDBPadstack' object has no attribute 'get_properties'. Did you mean: 'hole_properties'?

I think it is depending on Cpython env.

**Comment by hui-zhou-a** [comment]
@aohta2021 it isa bug. DL1 is an IO component from database. It needs to be changed to inductor before setting enabled. I made a pr to fix this

**Comment by aohta2021** [comment]
@hui-zhou-a 

I added new TEST case as To_TEST_1223.zip
and no error PyAEDT enviromnet as venv310_OK.zip

This has not been fixed yet.
Please run_EDB.bat after changed Line 20 and Line 30 for your install environment.
Error can avoid after setting old updated PyAEDT( Which is setting venv_310_OK)

I think this issue is depending PyAEDT environment.
Please check it again.
[To_TEST_1223.zip](https://github.com/user-attachments/files/18224325/To_TEST_1223.zip)

https://ansys-my.sharepoint.com/:u:/p/akira_ohta/EZjWAtUSoEpDgbmQQtK145wBIF5redDbnCdrGlMCmtDq1g?e=4iwhGE

**Comment by aohta2021** [comment]
The issue is 
edb.configuration.run(fix_padstack_def=True)
It makes error on the latest PyAEDT.
If it is changed fix_padstack_def=False, Script ruin successful.
But the design could not keep anti pad hole and it makes DC error on analysis.

**Comment by hui-zhou-a** [comment]
#
